### ISSUE TITLE
Connectivity issues

### ISSUE THREAD

**Issue by JakobTewes** [hvalev/dht22mqtt-homeassistant-docker#54]
Heyhey,

since a few, I´ve got problems with the containers MQTT connectivity although MQTT is running and reachable from the docker host. Seeing this error message:

`Traceback (most recent call last):`
`  File "//dht22mqtt.py", line 216, in <module>`
`    client.connect(mqtt_brokeraddr, keepalive=dht22mqtt_refresh*60)`
`  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect`
`    return self.reconnect()`
`  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1044, in reconnect`
`    sock = self._create_socket_connection()`
`  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection`
`    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)`
`  File "/usr/local/lib/python3.9/socket.py", line 843, in create_connection`
`    raise err`
`  File "/usr/local/lib/python3.9/socket.py", line 831, in create_connection`
 `   sock.connect(sa)`
`socket.timeout: timed out`

Maybe someone can help?

Thanks and regards

Jakob

**Comment by hvalev** [comment]
Hey @JakobTewes, I haven't used this container myself in some time. I'll take a look soon, likely sometime next week. Meanwhile, can you try adding `network_mode: "host"` to the docker compose file and also check if your mqtt network is configured to accept new devices?
